kind: pipeline
name: default

steps:
   -  name: test
      image: golang:1.13
      environment:
         GOPROXY: https://goproxy.cn
      commands:
         - go build -mod=vendor
         - go test -mod=vendor -v -race -coverprofile=coverage.txt -covermode=atomic ./...